// packages/vue/examples/App.vue
<script setup lang="ts">
import { ref } from "vue";
import { GAlert, GButton, GCard, GDialog, GardenerPart, GardenerProvider, useGardenerBehavior, type GardenerBehaviorInstance, type GardenerComponentPublicInstance } from "@gardenerim/vue";

const dialog = ref<GardenerComponentPublicInstance | null>(null);
interface DialogInstance extends GardenerBehaviorInstance { open(): void }
const { instance } = useGardenerBehavior<DialogInstance>(dialog, "dialog");
const open = () => instance.value?.open?.();
</script>

<template>
  <GardenerProvider class="g-container g-py-10" theme="garden" mode="light" shape="subtle" density="comfortable">
    <main class="g-stack g-gap-6">
      <header>
        <span class="g-badge">Vue 1.0.0</span>
        <h1>Gardener Vue</h1>
        <p class="g-text-muted">506 个组件、66 种行为和完整类型支持。</p>
      </header>

      <GAlert state="info">这是 Gardener CSS 与 Vue 3 的官方适配层。</GAlert>

      <GCard>
        <GardenerPart name="card-header"><strong>开箱即用</strong></GardenerPart>
        <GardenerPart name="card-body">
          <p>组件支持 variant、state、config、slots、原生 attributes 和运行时实例访问。</p>
          <GButton variant="primary" @click="open">打开对话框</GButton>
        </GardenerPart>
      </GCard>

      <GDialog ref="dialog" hidden>
        <div class="g-dialog" aria-labelledby="demo-title">
          <h2 id="demo-title">Gardener Vue 对话框</h2>
          <p>底层复用 Gardener 的焦点管理、键盘和生命周期行为。</p>
          <GButton data-g-close variant="primary">完成</GButton>
        </div>
      </GDialog>
    </main>
  </GardenerProvider>
</template>

// packages/react/examples/App.tsx
import { useState } from "react";
import { GAlert, GButton, GCard, GInput, GardenerProvider, componentCatalog } from "@gardenerim/react";

export function App() {
  const [name, setName] = useState("Gardener");
  const [valueEvents, setValueEvents] = useState(0);
  return (
    <GardenerProvider theme="garden" mode="light" shape="subtle" density="comfortable">
      <main className="g-container g-py-8" style={{ maxWidth: "54rem" }}>
        <header className="g-mb-6">
          <span className="g-badge">React 1.0.0 Stable</span>
          <h1 className="g-mt-3">Gardener React</h1>
          <p>506 个组件、66 种行为、Web / Mobile / Desktop / Tauri / Electron。</p>
        </header>
        <GAlert state="success">官方 React 适配层已加载。</GAlert>
        <GCard className="g-mt-5 g-p-5">
          <label className="g-label" htmlFor="react-name">名称</label>
          <GInput id="react-name" value={name} onValueChange={(value) => { setName(String(value ?? "")); setValueEvents((count) => count + 1); }} />
          <div className="g-flex g-gap-2 g-mt-4">
            <GButton variant="primary" onClick={() => setName("已保存")}>保存</GButton>
            <span className="g-badge" data-testid="value">{name}</span>
            <span className="g-badge" data-testid="value-events">{valueEvents}</span>
          </div>
        </GCard>
        <p className="g-mt-5" data-testid="catalog-count">{componentCatalog.length} components</p>
      </main>
    </GardenerProvider>
  );
}
